name: run script

on:
  push:
    branches-ignore: [main]
    # Remove the line above to run when pushing to master
  pull_request:
    branches: [main]

jobs:
  build:
    # Name the Job
    name: run script 2

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up node
        uses: action/setup-node@v2
        with:
          node-version": "14"
      - name: Install req
        run: npm install
      - name: Install ajv-cli
        run: npm install ajv-cli
      - name: Exec script
        run: |
          # make file runnable, might not be necessary
          chmod +x "script.sh"

          # run script
          "$./script.sh"
