name: Validate JSON (snapcart)

on:
  push:
    branches-ignore: [main]
    # Remove the line above to run when pushing to master
  pull_request:
    branches: [main]
jobs:
  validate_configurations:
    name: Validate configurations
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Validate BigQuery schema
        uses: snapcart/json-schema-validator@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          json_schema: ./clas/clas.json
          json_path_pattern: .*/examples/*clas.json$
          send_comment: true
          clear_comments: true
      - name: Validate other schema
        uses: snapcart/json-schema-validator@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          json_schema: ./intf/intf.json
          json_path_pattern: .*/examples/*intf.json$
