name: Validate JSON (snapcart)

on:
  pull_request:
    branches: [main]
jobs:
  validate_configurations:
    name: Validate configurations
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Validate CLAS schema
        uses: snapcart/json-schema-validator@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          json_schema: ./clas/clas.json
          json_path_pattern: .*/example/.*clas.json$
      - name: Validate NROB schema
        uses: snapcart/json-schema-validator@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          json_schema: ./nrob/nrob.json
          json_path_pattern: .*/example/.*nrob.json$
